### PR TITLE
Feature Implementation for #334

### PR DESCRIPTION
**Pull request by RaghavAwasthi**
# Lead Management Android
The amazing android app by JBOSS to manage contacts and record calls

## Suggested  Features
- The app does not have any feature to list all the calls which have been recorded by the user through *Lead Management Android*
- The app does not have an inbuilt media player to play these recorded calls
 - The app does not have any way of backing up these call recordings to *Google Drive*

## Implemented Features 
- The app now has an amazing list to show the list of call recordings  

-The app has an amazing media player to play these recorded calls right from within the app. The media player used is available inside Android API's so it doesnt increase the size of the app
However it supports almost all the features of common media players such as seeking.

whatsapp image 2018-12-10 at 3 28 46 am

- The App now also has an inbuilt Drive Backup Engine which gives you full control on the Call Recordings that you wish to backup.This makes the app different from the other apps which backup all your Call recordings. In LEAD Management you can tap on the specific Recordings you wish to backup to your drive account

## Updated UI 
whatsapp image 2018-12-10 at 3 28 46 am 2

## Hidden Storage of App Data
All user recordings are stored in a Hidden Folder to prevent any unauthorized modifications.Further security is enforced by specifying read only params while caching file on local Storage Hereby ensuring  Security of these recordings .
screenshot

This Pull request addresses issue #334

### CODE REVIEW

**Comment by bartekpacia** [comment]
Wow, I just want to say that this is amazing!

**Comment by RaghavAwasthi** [comment]
Thanks @bartekpacia

**Comment by the-dagger** [comment]
Wow, nice work!
@Lavanyagaur22 @krnblni @SyamSundarKirubakaran What do you think?

**Comment by RaghavAwasthi** [comment]
Thanks  @the-dagger It means alot

**Comment by SyamSundarKirubakaran** [comment]
@the-dagger let me take a look.!

**Comment by RaghavAwasthi** [comment]
@SyamSundarKirubakaran  I didn't get what you are trying to say.  I have used icon assets from https://material.io/tools/icons/?style=baseline So do you want me to make them a little grey  or increase their size or add some shadow effects or something else.  So that the code could be fit to be merged into master

**Comment by SyamSundarKirubakaran** [comment]
- If you were to keep blue as background tint for all the list items - change the icon colors to white
- If you were to keep background tint for all the list items - icon colors is a go 👍 
Plus a bit of testing has to be done on this like recording state change on **call hold** and so on.

**Comment by RaghavAwasthi** [comment]
Okay I am working on it . For testing I will be using OPPO A37 with android 8.1 API level 27
Changes to be introduced 
- Change of Icon assets from black to white
- Smooth edges of text (Additional Shadow , bold )
- Testing various call state 
- Testing on these devices
  - OPPO A37
  - VIVO V9
  - Samsung Galaxy neo

**Comment by RaghavAwasthi** [comment]
@SyamSundarKirubakaran @the-dagger  Have a look at the changes

whatsapp image 2018-12-10 at 3 28 46 am 1
whatsapp image 2018-12-10 at 3 28 46 am 2

**Comment by the-dagger** [comment]
Looks pretty neat!
Well done :) 💯

**Pull request merged**
