### PR TITLE
Travis Bug fix - Update .travis.yml

### PR DESCRIPTION
**Pull request by sidhyatikku**
#### Travis Bug Fix
* I don't know what I've done and how I've done, but the `.travis.yml` is now parseable and build is successful. 😄  🎉 

[Build Status](https://travis-ci.org/sidhyatikku/lead-management-android)

### CODE REVIEW

**Comment by aashutoshrathi** [comment]
Seriously!!.
Who was responsible for that build error?

**Comment by sidhyatikku** [comment]
@aashutoshrathi #338 had fixed the issue but then later #302 got merged. Initially the `blank space` was introduced in #149 

I'm still confused how PR #149 was merged.

**Comment by aashutoshrathi** [comment]
Yeah this looks good to me.

**Comment by the-dagger** [comment]
Yeah, my bad!
I need to be more careful 😅😆

**Pull request merged**
